backend:
  name: git-gateway
  branch: main # Ganti dengan 'master' jika branch utama GitHub Anda menggunakan nama master

media_folder: "assets/img/blog"
public_folder: "assets/img/blog"

collections:
  - name: "blog"
    label: "Artikel Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Artikel", name: "title", widget: "string" }
      - { label: "Tanggal Publish", name: "date", widget: "datetime" }
      - { label: "Gambar Utama", name: "image", widget: "image", required: false }
      - { label: "Ringkasan Singkat", name: "description", widget: "text" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }